DROP TABLE AuditLog;
CREATE TABLE AuditLog (
	userId				VARCHAR(30),	-- User ID
	name				VARCHAR(30),	-- User Name
	ip					VARCHAR(30),	-- User Ip
	category1			VARCHAR(20),	-- Category 1
	category1Name		VARCHAR(20),	-- Category 1 Name
	category2			VARCHAR(20),	-- Category 2
	category2Name		VARCHAR(20),	-- Category 2 Name
	category3			VARCHAR(20),	-- Category 3
	category3Name		VARCHAR(20),	-- Category 3 Name
	time				NUMERIC(20),		-- Audit Time
	description			VARCHAR(255),	-- Description
	status				VARCHAR(20)		-- Status
);

DROP TABLE LoginLog;
CREATE TABLE LoginLog (
	sessionId			VARCHAR(50) PRIMARY KEY,	-- 세션 ID
	id					VARCHAR(30),	-- User ID
	name				VARCHAR(30),	-- User Name
	loginDate			NUMERIC(20),	-- User Login Date (Time)
	ip					VARCHAR(20),	-- User Connection IP
	roleInstanceName	VARCHAR(50),	-- User Role Instance Name
	roleName			VARCHAR(50),	-- User Role Name
	logoutDate			NUMERIC(20),	-- User Logout Date (Time)
	status				VARCHAR(20)	-- User Status
);

DROP TABLE package_info;
CREATE TABLE package_info (
	installDate			TIMESTAMP NOT NULL,   -- 설치일(YYYY-MM-DD HH:MM:SS)
	equipinstanceName	VARCHAR(256) NOT NULL,	-- 장비의 인스턴스 이름
	packageInstance		VARCHAR(256) NOT NULL,  -- 패키지인스턴스
	ipaddr				VARCHAR(20),   -- IP
	packageInstanceName	VARCHAR(256),  -- 패키지인스턴스이름
	category			VARCHAR(256),  -- 범주
	arch				VARCHAR(256),  -- 아카이브
	version				VARCHAR(256),  -- 버전
	descr				VARCHAR(256)  -- 설명
);

DROP INDEX package_info_idx1;
CREATE UNIQUE INDEX package_info_idx1 ON package_info(
		installDate,equipinstanceName,packageInstance); 

ALTER TABLE FM_FaultClass DROP CONSTRAINT FM_FaultClass_pk CASCADE;
DROP TABLE FM_FaultClass;	 
CREATE TABLE FM_FaultClass (
	NAME				VARCHAR(64),
	DESCRIPTION			VARCHAR(255),
	MONITOR				INT,
	MESSAGE				VARCHAR(255),
	ISTT				NUMERIC(1),
	ISPREPROCESS		NUMERIC(1),
	PROBABLECAUSECODE	INT,
	CATEGORYCODE		INT,
	OTHERCATEGORYCODE	INT,
	SEVERITYCODE		INT,
	OTHERSEVERITYCODE	INT,
	TROUBLEADVICE		VARCHAR(255),
	CONSTRAINT FM_FaultClass_pk PRIMARY KEY(NAME)
);

ALTER TABLE FM_Snmp DROP CONSTRAINT FM_Snmp_pk CASCADE;
DROP TABLE FM_Snmp;
CREATE TABLE FM_Snmp (
	ID					VARCHAR(32),
	TIME1				NUMERIC(19),
	MESSAGE				VARCHAR(255),
	PROTOCOLNAME		VARCHAR(32),
	PROTOCOLVERSION		VARCHAR(32),
	IPADDRESS			VARCHAR(15),
	ENTERPRISE			VARCHAR(255),
	GENERICTYPE			INT,
	SPECIFICTYPE		INT,
--	VARBIND				BYTEA,
	CONSTRAINT FM_Snmp_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_Config_Backup DROP CONSTRAINT FM_Config_Backup_pk CASCADE;
DROP TABLE FM_Config_Backup;
CREATE TABLE FM_Config_Backup (
	ID				VARCHAR(32),
	SYSIPADDR		VARCHAR(15),	-- 장비IP
	SYSNAME			VARCHAR(255),	-- 장비명
	SYSKEY			VARCHAR(255),	-- parsing하여 장비유형 구함
	VENDOR			VARCHAR(255),	-- 벤더명
	MODEL			VARCHAR(255),	-- 모델명
	LOCCODE			VARCHAR(255),	-- 부서코드
	LOCNAME			VARCHAR(255),	-- 부서명
	TIME1			NUMERIC(19),	-- 백업시간
	CONFIGFILE		VARCHAR(255),	-- 백업파일명(fullpath)
	CONFIGTYPE		VARCHAR(64),	-- 백업항목(running-config, startup-config)
	FAILED			NUMERIC(1),		-- 1:실패, 0:성공
	DIFF			NUMERIC(1),		-- 1:변경, 0:동일함
	CONSTRAINT FM_Config_Backup_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_Check_Result DROP CONSTRAINT FM_Check_Result_pk CASCADE;
DROP TABLE FM_Check_Result;
CREATE TABLE FM_Check_Result (
	ID				VARCHAR(32),
	SYSIPADDR		VARCHAR(15),	-- 장비IP
	SYSNAME			VARCHAR(255),	-- 장비명
	SYSKEY			VARCHAR(255),	-- parsing하여 장비유형 구함
	VENDOR			VARCHAR(255),	-- 벤더명
	MODEL			VARCHAR(255),	-- 모델명
	LOCCODE			VARCHAR(255),	-- 부서코드
	LOCNAME			VARCHAR(255),	-- 부서명
	TIME1			NUMERIC(19),	-- 검사시간
	RESULTFILE		VARCHAR(255),	-- 결과파일명(fullpath)
	CHECKTYPE		VARCHAR(64),	-- 체크항목(hourly, daily, weekly, monthly)
	FAILED			NUMERIC(1),		-- 체크결과(1:실패, 0:성공)
	RESULT			NUMERIC(1),		-- 체크내용검사결과(1:정상, 0:장애)
	DIFF			NUMERIC(1),		-- 1:변경, 0:동일함
	CONSTRAINT FM_Check_Result_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_Syslog DROP CONSTRAINT FM_Syslog_pk CASCADE;
DROP TABLE FM_Syslog;
CREATE TABLE FM_Syslog (
	ID				VARCHAR(32),
	PRIORITY		INT,			-- 등급
	FACILITY		INT,			-- (아직 사용안함)
	MESSAGE			VARCHAR(2048),	-- SYSLOG 내용
	LOCCODE			VARCHAR(255),	-- 부서코드
	LOCNAME			VARCHAR(255),	-- 부서명
	SYSIPADDR		VARCHAR(15),	-- 장비IP
	SYSNAME			VARCHAR(255),	-- 장비명
	SYSKEY			VARCHAR(255),	-- parsing하여 장비유형 구함
	TIME1			NUMERIC(19),	-- 발생시간
	FAULTCLASS		VARCHAR(64),	-- 장애명 (아직 사용안함)
	ISFAULT			NUMERIC(1),		-- 1:장애, 0:로그
	CONSTRAINT FM_Syslog_pk PRIMARY KEY(ID)
); 

ALTER TABLE FM_Forelog DROP CONSTRAINT FM_Forelog_pk CASCADE;
DROP TABLE FM_Forelog;
CREATE TABLE FM_Forelog (
	ID			VARCHAR(32),
	PRIORITY		INT,			-- 등급
	FACILITY		INT,			-- (아직 사용안함)
	MESSAGE			VARCHAR(2048),	-- SYSLOG 내용
	LOCCODE			VARCHAR(255),	-- 부서코드
	LOCNAME			VARCHAR(255),	-- 부서명
	SYSIPADDR		VARCHAR(15),	-- 장비IP
	SYSNAME			VARCHAR(255),	-- 장비명
	SYSKEY			VARCHAR(255),	-- parsing하여 장비유형 구함
	SUBKEY			VARCHAR(255),	-- parsing하여 Logical device 유형 구함
	TIME1			NUMERIC(19),	-- 발생시간
	RMSE			NUMERIC,	-- 예측 정확도
	FAULTCLASS		VARCHAR(64),	-- 장애명 (아직 사용안함)
	ISFAULT			NUMERIC(1),		-- 1:장애, 0:로그
	CONSTRAINT FM_Forelog_pk PRIMARY KEY(ID)
); 

ALTER TABLE FM_Syslog_Pattern DROP CONSTRAINT FM_Syslog_Pattern_pk CASCADE;
DROP TABLE FM_Syslog_Pattern;
CREATE TABLE FM_Syslog_Pattern (
	FAULTCLASS		VARCHAR(64),	-- SYSLOG 알람
	DESCR			VARCHAR(255),	-- SYSLOG 알람 메시지
	PATTERN			VARCHAR(255),	-- 문자열 패턴
	SEVERITY		INT,			-- 알람 등급
	ISHOLD			INT,			-- 적용/미적용
	CONSTRAINT FM_Syslog_Pattern_pk PRIMARY KEY(FAULTCLASS)
);

ALTER TABLE FM_Syslog_Search DROP CONSTRAINT FM_Syslog_Search_pk CASCADE;
DROP TABLE FM_Syslog_Search;
CREATE TABLE FM_Syslog_Search (
	ID				VARCHAR(32),	-- SYSLOG SEARCH PK
	DESCR			VARCHAR(255),	-- SYSLOG SEARCH 패턴명
	PATTERN			VARCHAR(255),	-- SYSLOG SEARCH 패턴
	CONSTRAINT FM_Syslog_Search_pk PRIMARY KEY(ID)
);   

ALTER TABLE FM_Trap DROP CONSTRAINT FM_Trap_pk CASCADE;
DROP TABLE FM_Trap;
CREATE TABLE FM_Trap (
	ID				VARCHAR(32),
	MESSAGE			VARCHAR(2048),	-- Trap 내용
	PROTOCOLNAME	VARCHAR(32),	-- 미사용
	PROTOCOLVERSION VARCHAR(32),	-- 미사용
	ENTERPRISE		VARCHAR(255),	-- enterprise oid
	GENERICTYPE		INT,			-- generic type num
	SPECIFICTYPE	INT,			-- specific type num
	LOCCODE			VARCHAR(255),	-- 부서코드
	LOCNAME			VARCHAR(255),	-- 부서명
	SYSIPADDR		VARCHAR(15),	-- 장비IP
	SYSNAME			VARCHAR(255),	-- 장비명
	SYSKEY			VARCHAR(255),	-- parsing하여 장비유형 구함
	TIME1			NUMERIC(19),	-- 발생시간
	FAULTCLASS		VARCHAR(64),	-- 장애명 (아직 사용안함)
	ISFAULT			NUMERIC(1),		-- 1:장애, 0:로그
	CONSTRAINT FM_Trap_pk PRIMARY KEY(ID)
); 

ALTER TABLE FM_InstanceCreation DROP CONSTRAINT FM_InstanceCreation_pk CASCADE;
DROP TABLE FM_InstanceCreation;
CREATE TABLE FM_InstanceCreation (
	ID				VARCHAR(32),
	TIME1			NUMERIC(19),
	MESSAGE			VARCHAR(255),
	INSTANCEKEY		VARCHAR(255),
	INSTANCEID		VARCHAR(255),
	CONTAINMENT		VARCHAR(255),
	ISASSOCIATION	NUMERIC(1),
	CURRENTMOINST	BYTEA,
	CONSTRAINT FM_InstanceCreation_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_InstanceDeletion DROP CONSTRAINT FM_InstanceDeletion_pk CASCADE;
DROP TABLE FM_InstanceDeletion;
CREATE TABLE FM_InstanceDeletion (
	ID				VARCHAR(32),
	TIME1			NUMERIC(19),
	MESSAGE			VARCHAR(255),
	INSTANCEKEY		VARCHAR(255),
	INSTANCEID		VARCHAR(255),
	CONTAINMENT		VARCHAR(255),
	ISASSOCIATION	NUMERIC(1),
	CURRENTMOINST	BYTEA,
	CONSTRAINT FM_InstanceDeletion_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_InstanceModification DROP CONSTRAINT FM_InstanceModification_pk CASCADE;
DROP TABLE FM_InstanceModification;
CREATE TABLE FM_InstanceModification (
	ID				VARCHAR(32),
	TIME1			NUMERIC(19),
	MESSAGE			VARCHAR(255),
	INSTANCEKEY		VARCHAR(255),
	INSTANCEID		VARCHAR(255),
	CONTAINMENT		VARCHAR(255),
	ISASSOCIATION	NUMERIC(1),
	CURRENTMOINST	BYTEA,
	PREVIOUSMOINST	BYTEA,
	CONSTRAINT FM_InstanceModification_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_ClassCreation DROP CONSTRAINT FM_ClassCreation_pk CASCADE;
DROP TABLE FM_ClassCreation;
CREATE TABLE FM_ClassCreation (
	ID				VARCHAR(32),
	TIME1			NUMERIC(19),
	MESSAGE			VARCHAR(255),
	CLASSNAME		VARCHAR(255),
	ISASSOCIATION	NUMERIC(1),
	CURRENTCLASSDEF	BYTEA,
	CONSTRAINT FM_ClassCreation_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_ClassDeletion DROP CONSTRAINT FM_ClassDeletion_pk CASCADE;
DROP TABLE FM_ClassDeletion;
CREATE TABLE FM_ClassDeletion (
	ID				VARCHAR(32),
	TIME1			NUMERIC(19),
	MESSAGE			VARCHAR(255),
	CLASSNAME		VARCHAR(255),
	ISASSOCIATION	NUMERIC(1),
	CURRENTCLASSDEF	BYTEA,
	CONSTRAINT FM_ClassDeletion_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_ClassModification DROP CONSTRAINT FM_ClassModification_pk CASCADE;
DROP TABLE FM_ClassModification;
CREATE TABLE FM_ClassModification (
	ID					VARCHAR(32),
	TIME1				NUMERIC(19),
	MESSAGE				VARCHAR(255),
	CLASSNAME			VARCHAR(255),
	ISASSOCIATION		NUMERIC(1),
	CURRENTCLASSDEF		BYTEA,
	PREVIOUSClassDef	BYTEA,
	CONSTRAINT FM_ClassModification_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_Alert DROP CONSTRAINT FM_Alert_pk CASCADE;
DROP TABLE FM_Alert;
CREATE TABLE FM_Alert (
	ID					VARCHAR(32),
	TIME1				NUMERIC(19),
	MESSAGE				VARCHAR(255),
	FAULTCLASSNAME		VARCHAR(64),
	STATUS				INT,
	CLOSETIME			NUMERIC(19),
	DURATION			NUMERIC(19),
	SEVERITY			INT,
	OTHERSEVERITY		INT,
	SEVERITYTRENDING	INT,
	TIMES				INT,
	INSTANCEKEY			VARCHAR(255),
	CONTAINMENT			VARCHAR(255),
	LOCATIONCODE		VARCHAR(255),
	LOCATIONNAME		VARCHAR(255),
	CREATEOPER			VARCHAR(64),
	CLEAROPER			VARCHAR(64),
	ALERTINGMO			BYTEA,
	ALERTINGMONAMEATTRIBUTE	VARCHAR(255),
	SYSTEMIPADDR		VARCHAR(20),
	SYSTEMKEY			VARCHAR(255),
	SYSTEMNAME			VARCHAR(255),
	TRACE1				VARCHAR(255),
	SNAPSHOT			VARCHAR(1000),
	CORRELATEDNOTIFICATION	BYTEA,
	CONSTRAINT FM_Alert_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_ThresholdAlert DROP CONSTRAINT FM_ThresholdAlert_pk CASCADE;
DROP TABLE FM_ThresholdAlert;
CREATE TABLE FM_ThresholdAlert (
	ID					VARCHAR(32),
	TIME1				NUMERIC(19),
	MESSAGE				VARCHAR(255),
	FAULTCLASSNAME		VARCHAR(64),
	STATUS				INT,
	CLOSETIME			NUMERIC(19),
	DURATION			NUMERIC(19),
	SEVERITY			INT,
	OTHERSEVERITY		INT,
	SEVERITYTRENDING	INT,
	TIMES				INT,
	INSTANCEKEY			VARCHAR(255),
	CONTAINMENT			VARCHAR(255),
	LOCATIONCODE		VARCHAR(255),
	LOCATIONNAME		VARCHAR(255),
	CREATEOPER			VARCHAR(64),
	CLEAROPER			VARCHAR(64),
	ALERTINGMO			BYTEA,
	THRESHOLDVALUE		BYTEA,
	OBSERVEDVALUE		BYTEA,
	ALERTINGMONAMEATTRIBUTE	VARCHAR(255),
	SYSTEMIPADDR		VARCHAR(20),
	SYSTEMKEY			VARCHAR(255),
	SYSTEMNAME			VARCHAR(255),
	CORRELATEDNOTIFICATION	BYTEA,
	METRIC				VARCHAR(32),
	TRACE1				VARCHAR(255),
	SNAPSHOT			VARCHAR(1000),
	CONSTRAINT FM_ThresholdAlert_pk PRIMARY KEY(ID)
);

ALTER TABLE FM_OPENALERT_VIEW DROP CONSTRAINT FM_OPENALERT_VIEW_PK CASCADE;
DROP TABLE FM_OPENALERT_VIEW;
CREATE TABLE FM_OPENALERT_VIEW (
	ID					VARCHAR(32),
	TIME1				NUMERIC(19),
	MESSAGE				VARCHAR(255),
	TYPE1				VARCHAR(255),
	FAULTCLASSNAME		VARCHAR(64),
	STATUS				INT,
	CLOSETIME			NUMERIC(19),
	DURATION			NUMERIC(19),
	SEVERITY			INT,
	OTHERSEVERITY		INT,
	SEVERITYTRENDING	INT,
	TIMES				INT,
	INSTANCEKEY			VARCHAR(255),
	CONTAINMENT			VARCHAR(255),
	LOCATIONCODE		VARCHAR(255),
	LOCATIONNAME		VARCHAR(255),
	CREATEOPER			VARCHAR(64),
	CLEAROPER			VARCHAR(64),
	ALERTINGMONAMEATTRIBUTE	VARCHAR(255),
	SYSTEMIPADDR		VARCHAR(20),
	SYSTEMKEY			VARCHAR(255),
	SYSTEMNAME			VARCHAR(255),
	METRIC				VARCHAR(32),
	TRACE1				VARCHAR(255),
	SNAPSHOT			VARCHAR(1000),
	CONSTRAINT FM_OPENALERT_VIEW_PK PRIMARY KEY(ID)
);

ALTER TABLE FM_TroubleLog DROP CONSTRAINT FM_TroubleLog_pk CASCADE;
DROP TABLE FM_TroubleLog;
CREATE TABLE FM_TroubleLog (
	ID					VARCHAR(32),
	OPERATORNAME		VARCHAR(100),
	DESCRIPTION			VARCHAR(4000),
	CAUSE1				VARCHAR(100),
	CAUSE2				VARCHAR(100),
	FIXED1				VARCHAR(100),
	FIXED2				VARCHAR(100),
	STARTTIME			TIMESTAMP,
	FINISHTIME			TIMESTAMP,
	LOGINPUTTIME		TIMESTAMP,
	CONSTRAINT FM_TroubleLog_pk PRIMARY KEY(ID)
);

DROP TABLE FM_ALARMHISTORY;
CREATE TABLE FM_ALARMHISTORY (
	ALERTID				VARCHAR(32),
	ALARMTIME			TIMESTAMP,
	ALARMTARGET			VARCHAR(50),
	ALARMMEMO			VARCHAR(255),
	ALARMRESULT			VARCHAR(2),  -- 0: 성공 , 1:실패
	ALERTTIME			TIMESTAMP,	   -- 발생시에는 "발생시간", 복구시에는 "복구시간"
	MESSAGE				VARCHAR(255),
	FAULTCLASSNAME		VARCHAR(64),
	LOCATIONNAME		VARCHAR(32),
	LOCATIONCODE		VARCHAR(255),
	SYSTEMIPADDR		VARCHAR(20),
	SYSTEMNAME			VARCHAR(255),
	ALERTSTATUS			VARCHAR(2),
	TARGETID			VARCHAR(36)
);

ALTER TABLE ZIPCODE DROP CONSTRAINT ZIPCODE_pk CASCADE;
DROP TABLE ZIPCODE;
CREATE TABLE ZIPCODE (
	SEQ				VARCHAR(5),	 -- 숫자
	ZIPCODE			VARCHAR(7),	 -- 우편번호
	SIDO			VARCHAR(20),	-- 시도
	GUGUN			VARCHAR(15),	-- 구/군
	DONG			VARCHAR(52),	-- 동
	BUNJI			VARCHAR(17),	-- 번지
	CONSTRAINT ZIPCODE_pk PRIMARY KEY (SEQ)
);

ALTER TABLE IPSCANINFO  DROP CONSTRAINT IPSCANINFO_pk CASCADE;
DROP TABLE IPSCANINFO;
CREATE TABLE IPSCANINFO (
	IPADDRNO		NUMERIC,		   -- uniqueue key, 시간(밀리세컨드)으로 생성
	IPADDR			VARCHAR(20),	 -- 장비 ip 주소
	NAME			VARCHAR(255),	-- 장비명
	DEVNAME			VARCHAR(255),	-- 장비명-SYSNAME
	CUDATE			VARCHAR(12),	 -- 생성날짜: 2015-01-14 형식
	DESCR			VARCHAR(255),	-- 장비 설명
	MAIL			VARCHAR(64),	 -- Email
	TEL				VARCHAR(30),	 -- 전화번호
	MODEL			VARCHAR(50),	 -- 장비모델
	PORTNO			VARCHAR(50),	 -- 포트번호
	ADMINNAME		VARCHAR(20),	 -- 관리자 이름
	ADMINUNIT		VARCHAR(50),	 -- 관리자 소속
	MOBILENO		VARCHAR(20),	 -- 관리자 전화번호: 010-0000-0000 형식
	ETC				VARCHAR(100),	-- 기타 정보
	CONSTRAINT IPSCANINFO_pk PRIMARY KEY (IPADDRNO)
);

ALTER TABLE PM_SLBOIDTEMPLATE DROP CONSTRAINT PM_SLBOIDTEMPLATE_pk CASCADE;
DROP TABLE PM_SLBOIDTEMPLATE;
CREATE TABLE PM_SLBOIDTEMPLATE (
	ID					NUMERIC(38) NOT NULL,
	NAME				VARCHAR(64),
	DESCRIPTION			VARCHAR(128),
	CONSTRAINT PM_SLBOIDTEMPLATE_pk PRIMARY KEY (ID)
);

ALTER TABLE PM_SLBOID DROP CONSTRAINT PM_SLBOID_pk CASCADE;
DROP TABLE PM_SLBOID;
CREATE TABLE PM_SLBOID (
	ID	   				NUMERIC(38) NOT NULL,
	INSTANCENAME		VARCHAR(255),
	TEMPLATEID 			NUMERIC(38) NOT NULL,
	CONSTRAINT PM_SLBOID_pk PRIMARY KEY (ID)
);

ALTER TABLE PM_SLBOIDITEM DROP CONSTRAINT PM_SLBOIDITEM_pk CASCADE;
DROP TABLE PM_SLBOIDITEM;
CREATE TABLE PM_SLBOIDITEM (
	ITEM				VARCHAR(64) NOT NULL,
	DESCRIPTION			VARCHAR(128),
	CONSTRAINT PM_SLBOIDITEM_pk PRIMARY KEY (ITEM)
);

ALTER TABLE PM_SLBOIDTEMPLATETARGETTBL DROP CONSTRAINT PM_SLBOIDTEMPLATETARGETTBL_pk CASCADE;
DROP TABLE PM_SLBOIDTEMPLATETARGETTBL;
CREATE TABLE PM_SLBOIDTEMPLATETARGETTBL (
	ID					NUMERIC(38) NOT NULL,
	ITEM				VARCHAR(64) NOT NULL,
	OID					VARCHAR(128) NOT NULL,
	CALTYPE				VARCHAR(128) NOT NULL,
	CONSTRAINT PM_SLBOIDTEMPLATETARGETTBL_pk PRIMARY KEY (ID, ITEM)
);

DROP TABLE URLResponse_log;
CREATE TABLE URLResponse_log (
	logTime			NUMERIC NOT NULL,
	agentKey		VARCHAR(255),
	agentName		VARCHAR(255),
	agentIp			VARCHAR(255),
	urlName			VARCHAR(255),
	url				VARCHAR(255),
	port			VARCHAR(255),
	responseTime	NUMERIC,
	response_code	NUMERIC,	
	response_descr	VARCHAR(255),
	pingResTime		NUMERIC
);

ALTER TABLE FM_Trap_Pattern DROP CONSTRAINT FM_Trap_Pattern_pk CASCADE;
DROP TABLE FM_Trap_Pattern;
CREATE TABLE FM_Trap_Pattern (
	FAULTCLASS		VARCHAR(64),	   -- Trap FaultClassName
	OID				VARCHAR(64),	 	-- 	Enterprise OiD
	GENERIC			INT,	 			-- 	GenericType
	SPECIFIC		INT,	 			-- 	SpecificType
	DESCR			VARCHAR(255),	-- 	Trap 알람 메시지
	PATTERN			VARCHAR(2048),   -- 문자열 패턴
	SEVERITY		INT,			  -- 알람 등급
	ISHOLD			INT,			  -- 적용/미적용
	CONSTRAINT FM_Trap_Pattern_pk PRIMARY KEY(FAULTCLASS)
);

DROP TABLE IF EXISTS fm_forwardLog;
CREATE TABLE fm_forwardLog (
	target			VARCHAR(50)	NOT NULL DEFAULT 'ITSM',
	alertId			VARCHAR(32)	NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now()
);